// https://docs.github.com/de/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes
export const githubScopes = [
	'repo',
	'repo:status',
	'repo_deployment',
	'public_repo',
	'repo:invite',
	'security_events',
	'admin:repo_hook',
	'write:repo_hook',
	'read:repo_hook',
	'admin:org',
	'write:org',
	'read:org',
	'admin:public_key',
	'write:public_key',
	'read:public_key',
	'admin:org_hook',
	'gist',
	'notifications',
	'user',
	'read:user',
	'user:email',
	'user:follow',
	'project',
	'read:project',
	'delete_repo',
	'write:packages',
	'read:packages',
	'delete:packages',
	'admin:gpg_key',
	'write:gpg_key',
	'read:gpg_key',
	'codespace',
	'workflow',
	'read:audit_log'
] as const;

// https://discord.com/developers/docs/topics/oauth2#shared-resources-oauth2-scopes
export const discordScopes = [
	'activities.read',
	'activities.write',
	'applications.builds.read',
	'applications.builds.upload',
	'applications.commands',
	'applications.commands.permissions.update',
	'applications.commands.update',
	'applications.entitlements',
	'applications.store.update',
	'bot',
	'connections',
	'dm_channels.read',
	'email',
	'gdm.join',
	'guilds',
	'guilds.join',
	'guilds.members.read',
	'identify',
	'messages.read',
	'relationships.read',
	'rpc',
	'rpc.activities.write',
	'rpc.notifications.read',
	'rpc.voice.read',
	'rpc.voice.write',
	'role_connections.write',
	'voice',
	'webhook.incoming'
] as const;
